language: go
services:
  - docker
env:
  matrix
    - OS_TYPE=centos OS_VERSION=7

before_install:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi

after_success:
- test -n "$TRAVIS_TAG"

deploy:
- provider: script
  skip_cleanup: true
  script: make rpm
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

- provider: releases
  api_key:
       secure: "$TOKEN"
  file: 
       - /root/rpmbuild/RPMS/x86_64/docker-engine-1.12.7-1.el7.x86_64.rpm
       - /root/rpmbuild/RPMS/noarch/docker-engine-selinux-1.12.7-1.el7.noarch.rpm
  skip_cleanup: true
  on:
      tags: true
